/* ────────────────────────────────────────────────────────────
   catalog-data.js — shared Discover catalog + filter taxonomy

   Sourced from editing-mode.html (the old modal implementation);
   extracted so the new drawer-based Discover in editing-mode-new.html
   can reuse the same data without duplication. The old modal still
   has its copy inlined.
   ──────────────────────────────────────────────────────────── */

window.DISCOVER_CATALOG = [
  // Models
  { type:'Model',   label:'Llama-3-8B',                  by:'Meta',         color:'var(--dot-purple)', fn:'Text Generation',      fw:'PyTorch',    inputs:'Text, image, audio', outputs:'text',    views:'195.6k', downloads:'87.4k' },
  { type:'Model',   label:'stable-diffusion-xl-base-1.0', by:'stability AI', color:'var(--dot-yellow)', fn:'Text-to-image',        fw:'PyTorch',    inputs:'text, audio',        outputs:'image',   views:'120.5k', downloads:'78k' },
  { type:'Model',   label:'MiniCPM-V-2',                 by:'openbmb',      color:'var(--dot-green)',  fn:'Visual Question Answering', fw:null,    inputs:'text, image',        outputs:'text',    views:'33k',    downloads:'12.8k' },
  { type:'Model',   label:'RMBG-1.4',                    by:'briaai',       color:'var(--dot-red)',    fn:'Image Segmentation',   fw:null,         inputs:'image',              outputs:'image',   views:'5k',     downloads:'2.1k' },
  { type:'Model',   label:'Mixtral-8x7B-Instruct-v0.1',  by:'mistral AI',   color:'var(--dot-purple)', fn:'Text Generation',      fw:'PyTorch',    inputs:'text, image, audio', outputs:'text',    views:'13.1k',  downloads:'6.6k' },
  { type:'Model',   label:'MiniLM-L6-v2',                by:'Community',    color:'var(--dot-red)',    fn:'Sentence Similarity',  fw:'PyTorch',    inputs:'text',               outputs:'text, ID', views:'21.5k',  downloads:'59k' },
  { type:'Model',   label:'SDXL-Lightning',              by:'ByteDance',    color:'var(--dot-red)',    fn:'Text-to-image',        fw:'safetensor', inputs:'text',               outputs:'image',   views:'44k',    downloads:'31k' },
  { type:'Model',   label:'MRI-DEMO',                    by:'a_polar_bear', color:'var(--dot-blue)',   fn:'Image Segmentation',   fw:null,         inputs:'image',              outputs:'image',   views:'5k',     downloads:'2.1k' },
  { type:'Model',   label:'noise2recon-release',         by:'arjundd',      color:'var(--dot-green)',  fn:'Image Denoiser',       fw:null,         inputs:'text, image',        outputs:'text',    views:'33k',    downloads:'12.8k' },
  { type:'Model',   label:'MRI-Skull-Segmentation',      by:'NeuronZero',   color:'var(--dot-purple)', fn:'Image Classification', fw:null,         inputs:'image',              outputs:'image',   views:'13.1k',  downloads:'6.6k' },
  { type:'Model',   label:'mri-autoencoder-v0.1',        by:'Microsoft',    color:'var(--dot-yellow)', fn:'Diffuser',             fw:'safetensor', inputs:'text',               outputs:'text, ID', views:'21.5k',  downloads:'59k' },
  { type:'Model',   label:'mri-assistant',               by:'mav735',       color:'var(--dot-yellow)', fn:'Image Classification', fw:'PyTorch',    inputs:'text, audio',        outputs:'image',   views:'120.5k', downloads:'78k' },
  { type:'Model',   label:'MRI-Image-Priors',            by:'Guanxiong',    color:'var(--dot-red)',    fn:'Image Priors',         fw:null,         inputs:'Text, image, audio', outputs:'text',    views:'195.6k', downloads:'87.4k' },
  { type:'Model',   label:'mri-sd-v2_base-512-bs128',    by:'zach_shaw',    color:'var(--dot-red)',    fn:'Diffuser',             fw:null,         inputs:'text',               outputs:'image',   views:'8.2k',   downloads:'4.1k' },
  { type:'Model',   label:'PET-Skull-Segmentation',      by:'RazLab',       color:'var(--dot-red)',    fn:'Image Segmentation',   fw:'PyTorch',    inputs:'image',              outputs:'image',   views:'22k',    downloads:'9k' },
  { type:'Model',   label:'PET-Brain-Classification',    by:'RazLab',       color:'var(--dot-red)',    fn:'Image Classification', fw:'PyTorch',    inputs:'image',              outputs:'label',   views:'18k',    downloads:'7.5k' },
  { type:'Model',   label:'ObstacleScan Detection',      by:'Waymo',        color:'var(--dot-green)',  fn:'Object Detection',     fw:'PyTorch',    inputs:'binary',             outputs:'image',   views:'41k',    downloads:'22k' },
  { type:'Model',   label:'LaneVision Detection',        by:'Waymo',        color:'var(--dot-red)',    fn:'Lane Detection',       fw:'PyTorch',    inputs:'image',              outputs:'image',   views:'38k',    downloads:'19k' },
  { type:'Model',   label:'SignalVision Detection Node', by:'Waymo',        color:'var(--dot-purple)', fn:'Signal Recognition',   fw:'PyTorch',    inputs:'image',              outputs:'binary',  views:'29k',    downloads:'14k' },
  { type:'Model',   label:'Whisper-large-v3',            by:'OpenAI',       color:'var(--dot-blue)',   fn:'Speech Recognition',   fw:'PyTorch',    inputs:'audio',              outputs:'text',    views:'210k',   downloads:'145k' },
  { type:'Model',   label:'GPT-4o-mini',                 by:'OpenAI',       color:'var(--dot-green)',  fn:'Text Generation',      fw:'PyTorch',    inputs:'text, image',        outputs:'text',    views:'410k',   downloads:'230k' },
  { type:'Model',   label:'Claude-3.5-Sonnet',           by:'Anthropic',    color:'var(--dot-purple)', fn:'Text Generation',      fw:'PyTorch',    inputs:'text, image',        outputs:'text',    views:'340k',   downloads:'180k' },
  { type:'Model',   label:'Gemini-1.5-Pro',              by:'Google DeepMind', color:'var(--dot-yellow)', fn:'Text Generation',  fw:'TensorFlow', inputs:'text, image, video', outputs:'text',    views:'290k',   downloads:'150k' },
  { type:'Model',   label:'Llama-3-70B',                 by:'Meta',         color:'var(--dot-purple)', fn:'Text Generation',      fw:'PyTorch',    inputs:'text',               outputs:'text',    views:'250k',   downloads:'130k' },
  { type:'Model',   label:'Qwen2-72B-Instruct',          by:'Alibaba',      color:'var(--dot-red)',    fn:'Text Generation',      fw:'PyTorch',    inputs:'text',               outputs:'text',    views:'95k',    downloads:'48k' },
  { type:'Model',   label:'Phi-3-Medium',                by:'Microsoft',    color:'var(--dot-green)',  fn:'Text Generation',      fw:'PyTorch',    inputs:'text',               outputs:'text',    views:'62k',    downloads:'32k' },
  { type:'Model',   label:'DeepSeek-Coder-V2',           by:'DeepSeek',     color:'var(--dot-purple)', fn:'Code Generation',      fw:'PyTorch',    inputs:'text',               outputs:'text',    views:'78k',    downloads:'41k' },
  { type:'Model',   label:'StarCoder2-15B',              by:'Hugging Face', color:'var(--dot-yellow)', fn:'Code Generation',      fw:'PyTorch',    inputs:'text',               outputs:'text',    views:'54k',    downloads:'26k' },
  { type:'Model',   label:'CodeLlama-34B',               by:'Meta',         color:'var(--dot-blue)',   fn:'Code Generation',      fw:'PyTorch',    inputs:'text',               outputs:'text',    views:'48k',    downloads:'22k' },
  { type:'Model',   label:'BGE-Large-en-v1.5',           by:'BAAI',         color:'var(--dot-green)',  fn:'Sentence Similarity',  fw:'PyTorch',    inputs:'text',               outputs:'float',   views:'72k',    downloads:'56k' },
  { type:'Model',   label:'E5-mistral-7b',               by:'Microsoft',    color:'var(--dot-red)',    fn:'Sentence Similarity',  fw:'PyTorch',    inputs:'text',               outputs:'float',   views:'36k',    downloads:'19k' },
  { type:'Model',   label:'CLIP-ViT-L-14',               by:'OpenAI',       color:'var(--dot-blue)',   fn:'Image Embedding',      fw:'PyTorch',    inputs:'image, text',        outputs:'float',   views:'180k',   downloads:'95k' },
  { type:'Model',   label:'DINOv2-giant',                by:'Meta',         color:'var(--dot-purple)', fn:'Image Embedding',      fw:'PyTorch',    inputs:'image',              outputs:'float',   views:'41k',    downloads:'24k' },
  { type:'Model',   label:'YOLOv8-x',                    by:'Ultralytics',  color:'var(--dot-green)',  fn:'Object Detection',     fw:'PyTorch',    inputs:'image',              outputs:'bbox',    views:'220k',   downloads:'160k' },
  { type:'Model',   label:'DETR-ResNet-101',             by:'Meta',         color:'var(--dot-blue)',   fn:'Object Detection',     fw:'PyTorch',    inputs:'image',              outputs:'bbox',    views:'38k',    downloads:'18k' },
  { type:'Model',   label:'SAM-ViT-H',                   by:'Meta',         color:'var(--dot-yellow)', fn:'Image Segmentation',   fw:'PyTorch',    inputs:'image',              outputs:'image',   views:'160k',   downloads:'78k' },
  { type:'Model',   label:'Mask2Former',                 by:'Meta',         color:'var(--dot-red)',    fn:'Image Segmentation',   fw:'PyTorch',    inputs:'image',              outputs:'image',   views:'35k',    downloads:'16k' },
  { type:'Model',   label:'Swin-V2-Large',               by:'Microsoft',    color:'var(--dot-purple)', fn:'Image Classification', fw:'PyTorch',    inputs:'image',              outputs:'label',   views:'44k',    downloads:'21k' },
  { type:'Model',   label:'ConvNeXt-XL',                 by:'Meta',         color:'var(--dot-green)',  fn:'Image Classification', fw:'PyTorch',    inputs:'image',              outputs:'label',   views:'39k',    downloads:'18k' },
  { type:'Model',   label:'EfficientNet-v2-L',           by:'Google DeepMind', color:'var(--dot-blue)', fn:'Image Classification', fw:'TensorFlow', inputs:'image',            outputs:'label',   views:'52k',    downloads:'27k' },
  { type:'Model',   label:'PaliGemma-3B',                by:'Google DeepMind', color:'var(--dot-yellow)', fn:'Visual Question Answering', fw:'PyTorch', inputs:'image, text',  outputs:'text',    views:'28k',    downloads:'12k' },
  { type:'Model',   label:'LLaVA-NeXT-34B',              by:'Community',    color:'var(--dot-red)',    fn:'Visual Question Answering', fw:'PyTorch', inputs:'image, text',    outputs:'text',    views:'46k',    downloads:'22k' },
  { type:'Model',   label:'Flux.1-dev',                  by:'Black Forest Labs', color:'var(--dot-purple)', fn:'Text-to-image',    fw:'PyTorch',    inputs:'text',               outputs:'image',   views:'125k',   downloads:'71k' },
  { type:'Model',   label:'SD3-Medium',                  by:'Stability AI', color:'var(--dot-green)',  fn:'Text-to-image',        fw:'PyTorch',    inputs:'text',               outputs:'image',   views:'98k',    downloads:'54k' },
  { type:'Model',   label:'Kandinsky-3',                 by:'AI Forever',   color:'var(--dot-blue)',   fn:'Text-to-image',        fw:'PyTorch',    inputs:'text',               outputs:'image',   views:'22k',    downloads:'9.5k' },
  { type:'Model',   label:'Stable-Video-Diffusion',      by:'Stability AI', color:'var(--dot-yellow)', fn:'Text-to-video',        fw:'PyTorch',    inputs:'image',              outputs:'video',   views:'71k',    downloads:'38k' },
  { type:'Model',   label:'AnimateDiff-v3',              by:'Community',    color:'var(--dot-red)',    fn:'Text-to-video',        fw:'PyTorch',    inputs:'text',               outputs:'video',   views:'33k',    downloads:'15k' },
  { type:'Model',   label:'MusicGen-Large',              by:'Meta',         color:'var(--dot-purple)', fn:'Audio Generation',     fw:'PyTorch',    inputs:'text',               outputs:'audio',   views:'58k',    downloads:'26k' },
  { type:'Model',   label:'AudioLDM-2',                  by:'Community',    color:'var(--dot-green)',  fn:'Audio Generation',     fw:'PyTorch',    inputs:'text',               outputs:'audio',   views:'19k',    downloads:'8k' },
  { type:'Model',   label:'XTTS-v2',                     by:'Coqui',        color:'var(--dot-blue)',   fn:'Speech Synthesis',     fw:'PyTorch',    inputs:'text, audio',        outputs:'audio',   views:'88k',    downloads:'42k' },
  { type:'Model',   label:'VALL-E-X',                    by:'Microsoft',    color:'var(--dot-yellow)', fn:'Speech Synthesis',     fw:'PyTorch',    inputs:'text, audio',        outputs:'audio',   views:'24k',    downloads:'11k' },
  { type:'Model',   label:'Parakeet-TDT-1.1B',           by:'NVIDIA',       color:'var(--dot-red)',    fn:'Speech Recognition',   fw:'PyTorch',    inputs:'audio',              outputs:'text',    views:'32k',    downloads:'15k' },
  { type:'Model',   label:'NLLB-200-3.3B',               by:'Meta',         color:'var(--dot-purple)', fn:'Translation',          fw:'PyTorch',    inputs:'text',               outputs:'text',    views:'68k',    downloads:'31k' },
  { type:'Model',   label:'Marian-MT-en-de',             by:'Community',    color:'var(--dot-green)',  fn:'Translation',          fw:'PyTorch',    inputs:'text',               outputs:'text',    views:'21k',    downloads:'9k' },
  { type:'Model',   label:'BART-large-CNN',              by:'Meta',         color:'var(--dot-blue)',   fn:'Summarization',        fw:'PyTorch',    inputs:'text',               outputs:'text',    views:'56k',    downloads:'28k' },
  { type:'Model',   label:'Pegasus-XSum',                by:'Google DeepMind', color:'var(--dot-yellow)', fn:'Summarization',    fw:'TensorFlow', inputs:'text',               outputs:'text',    views:'31k',    downloads:'14k' },
  { type:'Model',   label:'BERT-base-uncased',           by:'Google DeepMind', color:'var(--dot-red)',  fn:'Text Classification',  fw:'PyTorch',    inputs:'text',               outputs:'label',   views:'340k',   downloads:'220k' },
  { type:'Model',   label:'DeBERTa-v3-Large',            by:'Microsoft',    color:'var(--dot-purple)', fn:'Text Classification',  fw:'PyTorch',    inputs:'text',               outputs:'label',   views:'82k',    downloads:'47k' },
  { type:'Model',   label:'RoBERTa-Sentiment',           by:'Community',    color:'var(--dot-green)',  fn:'Sentiment Analysis',   fw:'PyTorch',    inputs:'text',               outputs:'label',   views:'175k',   downloads:'140k' },
  { type:'Model',   label:'T5-Flan-XXL',                 by:'Google DeepMind', color:'var(--dot-blue)', fn:'Question Answering', fw:'PyTorch',    inputs:'text',               outputs:'text',    views:'66k',    downloads:'29k' },
  { type:'Model',   label:'RetinaNet-R50',               by:'Meta',         color:'var(--dot-yellow)', fn:'Object Detection',     fw:'PyTorch',    inputs:'image',              outputs:'bbox',    views:'26k',    downloads:'11k' },
  { type:'Model',   label:'PointNet++',                  by:'Stanford',     color:'var(--dot-red)',    fn:'3D Sensing',           fw:'PyTorch',    inputs:'point cloud',        outputs:'label',   views:'18k',    downloads:'7.5k' },
  { type:'Model',   label:'VoxelNet-LiDAR',              by:'Waymo',        color:'var(--dot-purple)', fn:'3D Sensing',           fw:'PyTorch',    inputs:'point cloud',        outputs:'bbox',    views:'14k',    downloads:'5.8k' },
  { type:'Model',   label:'DepthAnything-v2',            by:'Community',    color:'var(--dot-green)',  fn:'Depth Estimation',     fw:'PyTorch',    inputs:'image',              outputs:'image',   views:'45k',    downloads:'20k' },
  { type:'Model',   label:'MiDaS-v3.1',                  by:'Intel',        color:'var(--dot-blue)',   fn:'Depth Estimation',     fw:'PyTorch',    inputs:'image',              outputs:'image',   views:'29k',    downloads:'12k' },
  { type:'Model',   label:'TimeSformer-Large',           by:'Meta',         color:'var(--dot-yellow)', fn:'Action Recognition',   fw:'PyTorch',    inputs:'video',              outputs:'label',   views:'16k',    downloads:'6k' },
  { type:'Model',   label:'VideoMAE-v2',                 by:'Community',    color:'var(--dot-red)',    fn:'Action Recognition',   fw:'PyTorch',    inputs:'video',              outputs:'label',   views:'22k',    downloads:'9.2k' },
  { type:'Model',   label:'Informer-Forecast',           by:'Community',    color:'var(--dot-purple)', fn:'Time Series Forecasting', fw:'PyTorch', inputs:'float',              outputs:'float',   views:'34k',    downloads:'17k' },
  { type:'Model',   label:'NHiTS-Forecast',              by:'Community',    color:'var(--dot-green)',  fn:'Time Series Forecasting', fw:'PyTorch', inputs:'float',              outputs:'float',   views:'21k',    downloads:'8.8k' },
  { type:'Model',   label:'DQN-Atari',                   by:'DeepMind',     color:'var(--dot-blue)',   fn:'Reinforcement Learning', fw:'PyTorch',  inputs:'image',              outputs:'label',   views:'27k',    downloads:'10k' },
  { type:'Model',   label:'PPO-Humanoid',                by:'OpenAI',       color:'var(--dot-yellow)', fn:'Reinforcement Learning', fw:'PyTorch',  inputs:'float',              outputs:'float',   views:'18k',    downloads:'7k' },
  { type:'Model',   label:'ESM-2-650M',                  by:'Meta',         color:'var(--dot-red)',    fn:'Protein Folding',      fw:'PyTorch',    inputs:'string',             outputs:'float',   views:'24k',    downloads:'10k' },
  { type:'Model',   label:'AlphaFold-Light',             by:'DeepMind',     color:'var(--dot-purple)', fn:'Protein Folding',      fw:'JAX',        inputs:'string',             outputs:'float',   views:'38k',    downloads:'14k' },
  { type:'Model',   label:'DNABert-2',                   by:'Community',    color:'var(--dot-green)',  fn:'Genomics',             fw:'PyTorch',    inputs:'string',             outputs:'float',   views:'11k',    downloads:'4.2k' },
  // Datasets
  { type:'Dataset', label:'ImageNet-1k',                 by:'huggingface',  color:'var(--dot-blue)',   fn:'Image Classification', fw:null,         inputs:null,                 outputs:'image, label', views:'310k', downloads:'140k' },
  { type:'Dataset', label:'COCO-2017',                   by:'COCO Team',    color:'var(--dot-green)',  fn:'Object Detection',     fw:null,         inputs:null,                 outputs:'image, bbox',  views:'280k', downloads:'120k' },
  { type:'Dataset', label:'PET-Skull-Samples',           by:'RazLab',       color:'var(--dot-red)',    fn:'Medical Imaging',      fw:null,         inputs:null,                 outputs:'image',        views:'12k',  downloads:'5k' },
  { type:'Dataset', label:'Volume-Samples',              by:'RazLab',       color:'var(--dot-purple)', fn:'Medical Imaging',      fw:null,         inputs:null,                 outputs:'string',       views:'9k',   downloads:'3.5k' },
  { type:'Dataset', label:'Gene-Samples',                by:'RazLab',       color:'var(--dot-purple)', fn:'Genomics',             fw:null,         inputs:null,                 outputs:'string',       views:'7k',   downloads:'2.8k' },
  { type:'Dataset', label:'LiDAR Envir. Scans',          by:'Waymo',        color:'var(--dot-purple)', fn:'3D Sensing',           fw:null,         inputs:null,                 outputs:'binary',       views:'55k',  downloads:'31k' },
  { type:'Dataset', label:'StreetView Img Set',          by:'Waymo',        color:'var(--dot-red)',    fn:'Street Imagery',       fw:null,         inputs:null,                 outputs:'image',        views:'88k',  downloads:'44k' },
  { type:'Dataset', label:'VehicleTelemetry Data',       by:'Waymo',        color:'var(--dot-green)',  fn:'Telemetry',            fw:null,         inputs:null,                 outputs:'float',        views:'31k',  downloads:'18k' },
  { type:'Dataset', label:'Open Images V7',              by:'Google DeepMind', color:'var(--dot-yellow)', fn:'Object Detection', fw:null,         inputs:null,                 outputs:'image, bbox',  views:'210k', downloads:'98k' },
  { type:'Dataset', label:'LAION-5B',                    by:'LAION',        color:'var(--dot-blue)',   fn:'Text-to-image',        fw:null,         inputs:null,                 outputs:'image, text',  views:'520k', downloads:'130k' },
  { type:'Dataset', label:'LAION-400M',                  by:'LAION',        color:'var(--dot-purple)', fn:'Text-to-image',        fw:null,         inputs:null,                 outputs:'image, text',  views:'380k', downloads:'95k' },
  { type:'Dataset', label:'MS-MARCO',                    by:'Microsoft',    color:'var(--dot-red)',    fn:'Question Answering',   fw:null,         inputs:null,                 outputs:'text',         views:'120k', downloads:'60k' },
  { type:'Dataset', label:'SQuAD 2.0',                   by:'Stanford',     color:'var(--dot-green)',  fn:'Question Answering',   fw:null,         inputs:null,                 outputs:'text',         views:'340k', downloads:'180k' },
  { type:'Dataset', label:'GLUE',                        by:'Community',    color:'var(--dot-blue)',   fn:'Text Classification',  fw:null,         inputs:null,                 outputs:'text, label',  views:'210k', downloads:'115k' },
  { type:'Dataset', label:'SuperGLUE',                   by:'Community',    color:'var(--dot-yellow)', fn:'Text Classification',  fw:null,         inputs:null,                 outputs:'text, label',  views:'86k',  downloads:'42k' },
  { type:'Dataset', label:'Common Crawl — CC100',        by:'Community',    color:'var(--dot-purple)', fn:'Text Generation',      fw:null,         inputs:null,                 outputs:'text',         views:'150k', downloads:'72k' },
  { type:'Dataset', label:'The Pile',                    by:'EleutherAI',   color:'var(--dot-red)',    fn:'Text Generation',      fw:null,         inputs:null,                 outputs:'text',         views:'260k', downloads:'130k' },
  { type:'Dataset', label:'RedPajama-v2',                by:'Together',     color:'var(--dot-green)',  fn:'Text Generation',      fw:null,         inputs:null,                 outputs:'text',         views:'140k', downloads:'68k' },
  { type:'Dataset', label:'OpenWebText',                 by:'Community',    color:'var(--dot-blue)',   fn:'Text Generation',      fw:null,         inputs:null,                 outputs:'text',         views:'175k', downloads:'92k' },
  { type:'Dataset', label:'WikiText-103',                by:'Salesforce',   color:'var(--dot-yellow)', fn:'Text Generation',      fw:null,         inputs:null,                 outputs:'text',         views:'96k',  downloads:'50k' },
  { type:'Dataset', label:'C4 — Colossal Clean Crawl',   by:'Google DeepMind', color:'var(--dot-purple)', fn:'Text Generation', fw:null,         inputs:null,                 outputs:'text',         views:'220k', downloads:'110k' },
  { type:'Dataset', label:'LibriSpeech',                 by:'Community',    color:'var(--dot-red)',    fn:'Speech Recognition',   fw:null,         inputs:null,                 outputs:'audio, text',  views:'140k', downloads:'75k' },
  { type:'Dataset', label:'CommonVoice-17',              by:'Mozilla',      color:'var(--dot-green)',  fn:'Speech Recognition',   fw:null,         inputs:null,                 outputs:'audio, text',  views:'110k', downloads:'58k' },
  { type:'Dataset', label:'AudioSet',                    by:'Google DeepMind', color:'var(--dot-blue)', fn:'Audio Generation',   fw:null,         inputs:null,                 outputs:'audio, label', views:'72k',  downloads:'35k' },
  { type:'Dataset', label:'MUSDB18-HQ',                  by:'Community',    color:'var(--dot-yellow)', fn:'Audio Separation',     fw:null,         inputs:null,                 outputs:'audio',        views:'28k',  downloads:'12k' },
  { type:'Dataset', label:'Kinetics-700',                by:'DeepMind',     color:'var(--dot-purple)', fn:'Action Recognition',   fw:null,         inputs:null,                 outputs:'video, label', views:'86k',  downloads:'40k' },
  { type:'Dataset', label:'Something-Something-v2',      by:'Community',    color:'var(--dot-red)',    fn:'Action Recognition',   fw:null,         inputs:null,                 outputs:'video, label', views:'32k',  downloads:'14k' },
  { type:'Dataset', label:'WebVid-10M',                  by:'Community',    color:'var(--dot-green)',  fn:'Text-to-video',        fw:null,         inputs:null,                 outputs:'video, text',  views:'38k',  downloads:'17k' },
  { type:'Dataset', label:'KITTI-360',                   by:'KIT',          color:'var(--dot-blue)',   fn:'Autonomous Driving',   fw:null,         inputs:null,                 outputs:'image, point cloud', views:'95k', downloads:'47k' },
  { type:'Dataset', label:'nuScenes',                    by:'Motional',     color:'var(--dot-yellow)', fn:'Autonomous Driving',   fw:null,         inputs:null,                 outputs:'image, point cloud', views:'140k', downloads:'75k' },
  { type:'Dataset', label:'BDD100K',                     by:'Berkeley',     color:'var(--dot-purple)', fn:'Autonomous Driving',   fw:null,         inputs:null,                 outputs:'image, bbox',  views:'105k', downloads:'54k' },
  { type:'Dataset', label:'Cityscapes',                  by:'Community',    color:'var(--dot-red)',    fn:'Image Segmentation',   fw:null,         inputs:null,                 outputs:'image, label', views:'185k', downloads:'100k' },
  { type:'Dataset', label:'ADE20K',                      by:'MIT CSAIL',    color:'var(--dot-green)',  fn:'Image Segmentation',   fw:null,         inputs:null,                 outputs:'image, label', views:'72k',  downloads:'34k' },
  { type:'Dataset', label:'CelebA-HQ',                   by:'Community',    color:'var(--dot-blue)',   fn:'Image Generation',     fw:null,         inputs:null,                 outputs:'image, label', views:'96k',  downloads:'45k' },
  { type:'Dataset', label:'FFHQ',                        by:'NVIDIA',       color:'var(--dot-yellow)', fn:'Image Generation',     fw:null,         inputs:null,                 outputs:'image',        views:'130k', downloads:'64k' },
  { type:'Dataset', label:'MIMIC-CXR',                   by:'MIT Labs',     color:'var(--dot-purple)', fn:'Medical Imaging',      fw:null,         inputs:null,                 outputs:'image, text',  views:'41k',  downloads:'18k' },
  { type:'Dataset', label:'CheXpert',                    by:'Stanford',     color:'var(--dot-red)',    fn:'Medical Imaging',      fw:null,         inputs:null,                 outputs:'image, label', views:'56k',  downloads:'23k' },
  { type:'Dataset', label:'BraTS 2024',                  by:'Community',    color:'var(--dot-green)',  fn:'Medical Imaging',      fw:null,         inputs:null,                 outputs:'image',        views:'22k',  downloads:'9k' },
  { type:'Dataset', label:'UK Biobank — MRI',            by:'UK Biobank',   color:'var(--dot-blue)',   fn:'Medical Imaging',      fw:null,         inputs:null,                 outputs:'image',        views:'18k',  downloads:'6.5k' },
  { type:'Dataset', label:'ENCODE — Genomics',           by:'ENCODE',       color:'var(--dot-yellow)', fn:'Genomics',             fw:null,         inputs:null,                 outputs:'string',       views:'15k',  downloads:'5.4k' },
  { type:'Dataset', label:'UniProtKB',                   by:'UniProt',      color:'var(--dot-purple)', fn:'Protein Folding',      fw:null,         inputs:null,                 outputs:'string',       views:'33k',  downloads:'14k' },
  { type:'Dataset', label:'CIFAR-100',                   by:'Community',    color:'var(--dot-red)',    fn:'Image Classification', fw:null,         inputs:null,                 outputs:'image, label', views:'295k', downloads:'170k' },
  { type:'Dataset', label:'MNIST',                       by:'Community',    color:'var(--dot-green)',  fn:'Image Classification', fw:null,         inputs:null,                 outputs:'image, label', views:'410k', downloads:'260k' },
  { type:'Dataset', label:'Fashion-MNIST',               by:'Zalando',      color:'var(--dot-blue)',   fn:'Image Classification', fw:null,         inputs:null,                 outputs:'image, label', views:'220k', downloads:'140k' },
  { type:'Dataset', label:'FinBench-v2',                 by:'Community',    color:'var(--dot-yellow)', fn:'Time Series Forecasting', fw:null,     inputs:null,                 outputs:'float',        views:'12k',  downloads:'4.6k' },
  { type:'Dataset', label:'M5 Forecasting',              by:'Community',    color:'var(--dot-purple)', fn:'Time Series Forecasting', fw:null,     inputs:null,                 outputs:'float',        views:'34k',  downloads:'16k' },
  { type:'Dataset', label:'CDC Wastewater — US',         by:'CDC',          color:'var(--dot-red)',    fn:'Public Health',        fw:null,         inputs:null,                 outputs:'float',        views:'9k',   downloads:'3.2k' },
  { type:'Dataset', label:'WHO FluNet',                  by:'WHO',          color:'var(--dot-green)',  fn:'Public Health',        fw:null,         inputs:null,                 outputs:'float, string',views:'11k',  downloads:'4.1k' },
  // Logic
  { type:'Logic',   label:'Merged-Dataset',              by:'RazLab',       color:'var(--dot-yellow)', fn:'Data Fusion',          fw:null,         inputs:'string',             outputs:'string',       views:'14k',  downloads:'6k' },
  { type:'Logic',   label:'SmartPath Planning',          by:'Waymo',        color:'var(--dot-yellow)', fn:'Path Planning',        fw:null,         inputs:'image',              outputs:'string',       views:'27k',  downloads:'12k' },
  { type:'Logic',   label:'ObstacleShifter Net',         by:'Waymo',        color:'var(--dot-yellow)', fn:'Obstacle Avoidance',   fw:null,         inputs:'image',              outputs:'image',        views:'19k',  downloads:'9k' },
  { type:'Logic',   label:'Bayesian Fusion',             by:'Community',    color:'var(--dot-blue)',   fn:'Data Fusion',          fw:null,         inputs:'float',              outputs:'float',        views:'22k',  downloads:'9.8k' },
  { type:'Logic',   label:'Kalman Filter Block',         by:'Community',    color:'var(--dot-purple)', fn:'Signal Filtering',     fw:null,         inputs:'float',              outputs:'float',        views:'41k',  downloads:'19k' },
  { type:'Logic',   label:'Particle Filter',             by:'Community',    color:'var(--dot-green)',  fn:'Signal Filtering',     fw:null,         inputs:'float',              outputs:'float',        views:'16k',  downloads:'6.2k' },
  { type:'Logic',   label:'Decision Tree Router',        by:'Community',    color:'var(--dot-red)',    fn:'Decision Logic',       fw:null,         inputs:'float, label',       outputs:'label',        views:'28k',  downloads:'14k' },
  { type:'Logic',   label:'Threshold Alert',             by:'Community',    color:'var(--dot-yellow)', fn:'Decision Logic',       fw:null,         inputs:'float',              outputs:'label',        views:'36k',  downloads:'17k' },
  { type:'Logic',   label:'PID Controller',              by:'Community',    color:'var(--dot-blue)',   fn:'Control Systems',      fw:null,         inputs:'float',              outputs:'float',        views:'32k',  downloads:'15k' },
  { type:'Logic',   label:'MPC Controller',              by:'Community',    color:'var(--dot-purple)', fn:'Control Systems',      fw:null,         inputs:'float',              outputs:'float',        views:'19k',  downloads:'8k' },
  { type:'Logic',   label:'Rule-Based Safety Check',     by:'Waymo',        color:'var(--dot-green)',  fn:'Decision Logic',       fw:null,         inputs:'label, bbox',        outputs:'label',        views:'24k',  downloads:'11k' },
  { type:'Logic',   label:'Softmax Ensembler',           by:'Community',    color:'var(--dot-red)',    fn:'Data Fusion',          fw:null,         inputs:'float',              outputs:'float',        views:'18k',  downloads:'7k' },
  { type:'Logic',   label:'Weighted Voting',             by:'Community',    color:'var(--dot-yellow)', fn:'Data Fusion',          fw:null,         inputs:'label',              outputs:'label',        views:'14k',  downloads:'5.1k' },
  { type:'Logic',   label:'FFT Transform',               by:'Community',    color:'var(--dot-blue)',   fn:'Signal Processing',    fw:null,         inputs:'float',              outputs:'float',        views:'54k',  downloads:'29k' },
  { type:'Logic',   label:'Wavelet Denoiser',            by:'Community',    color:'var(--dot-purple)', fn:'Signal Processing',    fw:null,         inputs:'float',              outputs:'float',        views:'21k',  downloads:'8.2k' },
  { type:'Logic',   label:'NMS Post-Process',            by:'Community',    color:'var(--dot-green)',  fn:'Signal Processing',    fw:null,         inputs:'bbox',               outputs:'bbox',         views:'48k',  downloads:'23k' },
  { type:'Logic',   label:'ROI Cropper',                 by:'Community',    color:'var(--dot-red)',    fn:'Preprocessing',        fw:null,         inputs:'image, bbox',        outputs:'image',        views:'29k',  downloads:'13k' },
  { type:'Logic',   label:'Image Normalizer',            by:'Community',    color:'var(--dot-yellow)', fn:'Preprocessing',        fw:null,         inputs:'image',              outputs:'image',        views:'66k',  downloads:'33k' },
  { type:'Logic',   label:'Tokenizer — BPE',             by:'Hugging Face', color:'var(--dot-blue)',   fn:'Preprocessing',        fw:null,         inputs:'text',               outputs:'ID',           views:'85k',  downloads:'45k' },
  { type:'Logic',   label:'Tokenizer — SentencePiece',   by:'Google DeepMind', color:'var(--dot-purple)', fn:'Preprocessing',    fw:null,         inputs:'text',               outputs:'ID',           views:'42k',  downloads:'20k' },
  { type:'Logic',   label:'Label Smoothing',             by:'Community',    color:'var(--dot-green)',  fn:'Preprocessing',        fw:null,         inputs:'label',              outputs:'float',        views:'17k',  downloads:'6.4k' },
  { type:'Logic',   label:'Data Augmenter',              by:'Community',    color:'var(--dot-red)',    fn:'Preprocessing',        fw:null,         inputs:'image',              outputs:'image',        views:'71k',  downloads:'37k' },
  { type:'Logic',   label:'Mixup Block',                 by:'Community',    color:'var(--dot-yellow)', fn:'Preprocessing',        fw:null,         inputs:'image, label',       outputs:'image, label', views:'13k',  downloads:'4.9k' },
  { type:'Logic',   label:'Vector Quantizer',            by:'Community',    color:'var(--dot-blue)',   fn:'Data Fusion',          fw:null,         inputs:'float',              outputs:'ID',           views:'19k',  downloads:'7.8k' },
  { type:'Logic',   label:'K-Means Clusterer',           by:'Community',    color:'var(--dot-purple)', fn:'Clustering',           fw:null,         inputs:'float',              outputs:'label',        views:'38k',  downloads:'18k' },
  { type:'Logic',   label:'DBSCAN Clusterer',            by:'Community',    color:'var(--dot-green)',  fn:'Clustering',           fw:null,         inputs:'float',              outputs:'label',        views:'23k',  downloads:'9.6k' },
  { type:'Logic',   label:'Moving Average',              by:'Community',    color:'var(--dot-red)',    fn:'Signal Filtering',     fw:null,         inputs:'float',              outputs:'float',        views:'62k',  downloads:'30k' },
  { type:'Logic',   label:'Anomaly Detector',            by:'Community',    color:'var(--dot-yellow)', fn:'Decision Logic',       fw:null,         inputs:'float',              outputs:'label',        views:'44k',  downloads:'21k' },
  { type:'Logic',   label:'Semantic Router',             by:'Community',    color:'var(--dot-blue)',   fn:'Decision Logic',       fw:null,         inputs:'text',               outputs:'label',        views:'27k',  downloads:'12k' },
  { type:'Logic',   label:'Output Aggregator',           by:'Community',    color:'var(--dot-purple)', fn:'Data Fusion',          fw:null,         inputs:'float, label',       outputs:'label',        views:'16k',  downloads:'5.8k' },
  { type:'Logic',   label:'Confidence Gate',             by:'Community',    color:'var(--dot-green)',  fn:'Decision Logic',       fw:null,         inputs:'float',              outputs:'label',        views:'31k',  downloads:'14k' },
  { type:'Logic',   label:'JSON Schema Validator',       by:'Community',    color:'var(--dot-red)',    fn:'Preprocessing',        fw:null,         inputs:'string',             outputs:'string',       views:'18k',  downloads:'7.1k' },
  { type:'Logic',   label:'PII Redactor',                by:'Community',    color:'var(--dot-yellow)', fn:'Preprocessing',        fw:null,         inputs:'text',               outputs:'text',         views:'24k',  downloads:'11k' },
];

window.DISCOVER_FILTERS = {
  Function: ['Text Generation', 'Text Classification', 'Sentiment Analysis', 'Question Answering', 'Summarization', 'Translation', 'Sentence Similarity',
             'Image Classification', 'Image Segmentation', 'Object Detection', 'Image Embedding', 'Image Denoiser', 'Image Priors', 'Depth Estimation',
             'Text-to-image', 'Text-to-video', 'Image Generation',
             'Speech Recognition', 'Speech Synthesis', 'Audio Generation', 'Audio Separation',
             'Visual Question Answering', 'Action Recognition',
             'Lane Detection', 'Signal Recognition', 'Obstacle Avoidance', 'Path Planning', 'Autonomous Driving', 'Telemetry', 'Street Imagery', '3D Sensing',
             'Medical Imaging', 'Genomics', 'Protein Folding', 'Public Health',
             'Code Generation', 'Reinforcement Learning', 'Time Series Forecasting',
             'Data Fusion', 'Signal Filtering', 'Signal Processing', 'Decision Logic', 'Control Systems', 'Clustering', 'Preprocessing', 'Diffuser'],
  Category: ['Computer Vision', 'Natural Language Processing', 'Medical AI', 'Autonomous Driving', 'Multimodal', 'Audio Processing', 'Genomics & Biology', '3D & LiDAR', 'Image Generation', 'Reinforcement Learning', 'Data Engineering', 'Diffusion Models', 'Speech & Audio', 'Video Understanding', 'Time Series', 'Public Health', 'Developer Tools'],
  Input:    ['text', 'image', 'audio', 'binary', 'float', 'string', 'video', 'point cloud', 'label', 'bbox', 'ID'],
  Output:   ['text', 'image', 'binary', 'float', 'string', 'label', 'bbox', 'ID', 'point cloud', 'audio', 'video'],
  Owner:    ['Meta', 'Stability AI', 'Mistral AI', 'OpenAI', 'Anthropic', 'Google DeepMind', 'Hugging Face', 'Microsoft', 'ByteDance', 'RazLab', 'Waymo', 'NeuronZero', 'Community', 'openbmb', 'briaai', 'arjundd', 'Guanxiong', 'mav735', 'zach_shaw', 'COCO Team', 'a_polar_bear', 'Alibaba', 'DeepSeek', 'BAAI', 'Ultralytics', 'Black Forest Labs', 'AI Forever', 'Coqui', 'NVIDIA', 'Intel', 'Salesforce', 'Stanford', 'MIT CSAIL', 'MIT Labs', 'Berkeley', 'KIT', 'Motional', 'LAION', 'Mozilla', 'EleutherAI', 'Together', 'DeepMind', 'WHO', 'CDC', 'UK Biobank', 'UniProt', 'ENCODE', 'Zalando'],
};

window.DISCOVER_FN_TO_CAT = {
  'Text Generation':'Natural Language Processing', 'Sentence Similarity':'Natural Language Processing',
  'Text Classification':'Natural Language Processing', 'Sentiment Analysis':'Natural Language Processing',
  'Question Answering':'Natural Language Processing', 'Summarization':'Natural Language Processing',
  'Translation':'Natural Language Processing',
  'Visual Question Answering':'Multimodal', 'Image Embedding':'Multimodal',
  'Image Segmentation':'Computer Vision', 'Image Classification':'Computer Vision', 'Image Denoiser':'Computer Vision', 'Image Priors':'Computer Vision', 'Street Imagery':'Computer Vision', 'Depth Estimation':'Computer Vision',
  'Object Detection':'Autonomous Driving', 'Lane Detection':'Autonomous Driving', 'Signal Recognition':'Autonomous Driving', 'Obstacle Avoidance':'Autonomous Driving', 'Path Planning':'Autonomous Driving', 'Telemetry':'Autonomous Driving', 'Autonomous Driving':'Autonomous Driving',
  'Text-to-image':'Image Generation', 'Diffuser':'Image Generation', 'Image Generation':'Image Generation',
  'Text-to-video':'Video Understanding', 'Action Recognition':'Video Understanding',
  'Speech Recognition':'Speech & Audio', 'Speech Synthesis':'Speech & Audio', 'Audio Generation':'Speech & Audio', 'Audio Separation':'Speech & Audio',
  'Medical Imaging':'Medical AI', 'Public Health':'Public Health',
  'Data Fusion':'Data Engineering', 'Signal Filtering':'Data Engineering', 'Signal Processing':'Data Engineering', 'Preprocessing':'Data Engineering', 'Clustering':'Data Engineering',
  'Decision Logic':'Data Engineering', 'Control Systems':'Data Engineering',
  'Genomics':'Genomics & Biology', 'Protein Folding':'Genomics & Biology',
  '3D Sensing':'3D & LiDAR',
  'Code Generation':'Developer Tools',
  'Reinforcement Learning':'Reinforcement Learning',
  'Time Series Forecasting':'Time Series',
};
