// Rare-disease WGS interpretation pipeline — cohort joint calling, ACMG-style
// annotation, phenotype-driven prioritization, and clinical reporting. Mirrors
// how a genome center team would decompose work: reusable QC + genotyping +
// annotation subgraphs, then interpretation layers that consume joint VCFs,
// population databases, and HPO-encoded phenotypes.
window.PROJECT = {
  slug: 'human-genome-analysis',
  title: 'Human Genome Analysis',
  org: 'Broad Institute',
  tags: ['Genomics', 'Bioinformatics'],
  contributorCount: 29,
  contributors: [
    { letter: 'B', bg: '#0f172a', name: 'Broad Institute', role: 'Owner', pushes: 42 },
    { letter: 'P', bg: 'var(--avatar-2)', name: 'Priya R.', role: 'Admin', pushes: 11 },
    { letter: 'K', bg: 'var(--avatar-4)', name: 'Kim S.', role: 'Admin', pushes: 7 },
    { letter: 'A', bg: 'var(--avatar-6)', name: 'Alex M.', role: 'Contributor', pushes: 3 },
  ],
  othersCount: 25,
  othersPreview: 'Jordan Lee, Sam Okonkwo…',
  others: [
    { letter: 'J', bg: 'var(--avatar-3)', name: 'Jordan Lee' },
    { letter: 'S', bg: 'var(--avatar-5)', name: 'Sam Okonkwo' },
    { letter: 'L', bg: 'var(--avatar-1)', name: 'Lin Chen' },
    { letter: 'R', bg: 'var(--avatar-7)', name: 'Riley Park' },
  ],
  description: 'Whole-genome rare-variant workflow for a disease cohort: from FASTQ through GRCh38 alignment, joint gVCF genotyping, and VEP-based annotation, to phenotype-aware prioritization (HPO + trio structure), burden testing, CNV/SV overlays, and a signed clinical report with audit trail. Subgraphs bundle the sequencing core, the GATK-style joint-calling block, and the annotation stack so teams can iterate or swap tools without rewiring the interpretation layer.',
  canvasWidth: 2000,
  canvasHeight: 1040,
  viewZoom: 0.58,
  nodes: [
    /* ── Sequencing & alignment subgraph ───────────────────────── */
    { id: 'ng-demux', type: 'Dataset', label: 'FASTQ staging (demux)', color: 'var(--dot-blue)', user: { letter: 'P', color: 'var(--avatar-2)' }, x: 80, y: 120,
      outputs: [{ name: 'fastq_r1', type: 'string' }, { name: 'fastq_r2', type: 'string' }] },
    { id: 'ng-trim', type: 'Model', label: 'Adapter trim + QC', color: 'var(--dot-green)', user: { letter: 'K', color: 'var(--avatar-4)' }, x: 340, y: 100,
      inputs: [{ name: 'fastq_r1', type: 'string' }, { name: 'fastq_r2', type: 'string' }],
      outputs: [{ name: 'clean_r1', type: 'string' }, { name: 'clean_r2', type: 'string' }] },
    { id: 'ng-bwa', type: 'Model', label: 'BWA-MEM → GRCh38', color: 'var(--dot-green)', user: { letter: 'K', color: 'var(--avatar-4)' }, x: 600, y: 100,
      inputs: [{ name: 'clean_r1', type: 'string' }, { name: 'clean_r2', type: 'string' }],
      outputs: [{ name: 'aligned_bam', type: 'string' }] },
    { id: 'ng-dedup', type: 'Model', label: 'MarkDup + BQSR', color: 'var(--dot-green)', user: { letter: 'P', color: 'var(--avatar-2)' }, x: 860, y: 120,
      inputs: [{ name: 'aligned_bam', type: 'string' }],
      outputs: [{ name: 'analysis_bam', type: 'string' }] },

    /* ── Joint genotyping subgraph ─────────────────────────────── */
    { id: 'gt-hc', type: 'Model', label: 'HaplotypeCaller (gVCF)', color: 'var(--dot-purple)', user: { letter: 'A', color: 'var(--avatar-6)' }, x: 1120, y: 80,
      inputs: [{ name: 'analysis_bam', type: 'string' }],
      outputs: [{ name: 'sample_gvcf', type: 'string' }] },
    { id: 'gt-gdb', type: 'Model', label: 'GenomicsDBImport', color: 'var(--dot-purple)', user: { letter: 'A', color: 'var(--avatar-6)' }, x: 1380, y: 80,
      inputs: [{ name: 'sample_gvcf', type: 'string' }],
      outputs: [{ name: 'cohort_db', type: 'string' }] },
    { id: 'gt-gt', type: 'Model', label: 'GenotypeGVCFs (joint)', color: 'var(--dot-purple)', user: { letter: 'P', color: 'var(--avatar-2)' }, x: 1640, y: 100,
      inputs: [{ name: 'cohort_db', type: 'string' }],
      outputs: [{ name: 'joint_vcf', type: 'string' }] },

    /* ── Annotation subgraph ───────────────────────────────────── */
    { id: 'an-vep', type: 'Model', label: 'VEP + LOFTEE', color: 'var(--dot-yellow)', user: { letter: 'K', color: 'var(--avatar-4)' }, x: 120, y: 420,
      inputs: [{ name: 'pass_vcf', type: 'string' }],
      outputs: [{ name: 'vep_vcf', type: 'string' }] },
    { id: 'an-clin', type: 'Model', label: 'ClinVar + AlphaMissense', color: 'var(--dot-yellow)', user: { letter: 'K', color: 'var(--avatar-4)' }, x: 380, y: 420,
      inputs: [{ name: 'vep_vcf', type: 'string' }],
      outputs: [{ name: 'clin_vcf', type: 'string' }] },
    { id: 'an-acmg', type: 'Model', label: 'ACMG rule engine', color: 'var(--dot-yellow)', user: { letter: 'P', color: 'var(--avatar-2)' }, x: 640, y: 420,
      inputs: [{ name: 'clin_vcf', type: 'string' }],
      outputs: [{ name: 'classified', type: 'string' }] },

    /* ── Interpretation layer (outside subgraphs) ──────────────── */
    { id: 'vcf-gate', type: 'Logic', label: 'VCF QC gate (VQSR + depth)', color: 'var(--dot-red)', user: { letter: 'P', color: 'var(--avatar-2)' }, x: 1800, y: 120,
      inputs: [{ name: 'joint_vcf', type: 'string' }],
      outputs: [{ name: 'pass_vcf', type: 'string' }] },
    { id: 'ds-gnomad', type: 'Dataset', label: 'gnomAD v4 AF priors', color: 'var(--dot-blue)', user: { letter: 'B', color: '#0f172a' }, x: 80, y: 620,
      outputs: [{ name: 'af_table', type: 'string' }] },
    { id: 'ds-clinvar', type: 'Dataset', label: 'ClinVar release (GRCh38)', color: 'var(--dot-blue)', user: { letter: 'B', color: '#0f172a' }, x: 80, y: 760,
      outputs: [{ name: 'clinvar_tsv', type: 'string' }] },
    { id: 'ds-hpo', type: 'Dataset', label: 'HPO phenotype profiles', color: 'var(--dot-blue)', user: { letter: 'A', color: 'var(--avatar-6)' }, x: 80, y: 900,
      outputs: [{ name: 'hpo_json', type: 'string' }] },
    { id: 'ds-trios', type: 'Dataset', label: 'Trio / pedigree manifest', color: 'var(--dot-blue)', user: { letter: 'A', color: 'var(--avatar-6)' }, x: 340, y: 900,
      outputs: [{ name: 'pedigree', type: 'string' }] },
    { id: 'ds-cohort', type: 'Dataset', label: 'Study manifest & consents', color: 'var(--dot-blue)', user: { letter: 'B', color: '#0f172a' }, x: 340, y: 760,
      outputs: [{ name: 'cohort_yaml', type: 'string' }] },
    { id: 'md-prioritize', type: 'Model', label: 'Phenotype-aware prioritizer', color: 'var(--dot-red)', user: { letter: 'P', color: 'var(--avatar-2)' }, x: 600, y: 640,
      inputs: [
        { name: 'classified', type: 'string' },
        { name: 'hpo_json', type: 'string' },
        { name: 'pedigree', type: 'string' },
        { name: 'af_table', type: 'string' },
        { name: 'cohort_yaml', type: 'string' }
      ],
      outputs: [{ name: 'ranked_vars', type: 'string' }] },
    { id: 'md-exomiser', type: 'Model', label: 'Exomiser (phenotype + VCF)', color: 'var(--dot-purple)', user: { letter: 'K', color: 'var(--avatar-4)' }, x: 600, y: 780,
      inputs: [{ name: 'pass_vcf', type: 'string' }, { name: 'hpo_json', type: 'string' }],
      outputs: [{ name: 'exomiser_scores', type: 'string' }] },
    { id: 'md-burden', type: 'Model', label: 'Gene-burden (SKAT-O)', color: 'var(--dot-purple)', user: { letter: 'K', color: 'var(--avatar-4)' }, x: 900, y: 520,
      inputs: [{ name: 'pass_vcf', type: 'string' }, { name: 'af_table', type: 'string' }],
      outputs: [{ name: 'burden_q', type: 'float' }] },
    { id: 'md-cnv', type: 'Model', label: 'CNV depth (WGS bins)', color: 'var(--dot-purple)', user: { letter: 'K', color: 'var(--avatar-4)' }, x: 900, y: 240,
      inputs: [{ name: 'analysis_bam', type: 'string' }],
      outputs: [{ name: 'cnv_bed', type: 'string' }] },
    { id: 'md-sv', type: 'Model', label: 'SV merge (Manta + Delly)', color: 'var(--dot-purple)', user: { letter: 'A', color: 'var(--avatar-6)' }, x: 900, y: 380,
      inputs: [{ name: 'analysis_bam', type: 'string' }],
      outputs: [{ name: 'sv_vcf', type: 'string' }] },
    { id: 'md-fusion', type: 'Logic', label: 'SV + CNV + SNV + Exomiser fusion', color: 'var(--dot-yellow)', user: { letter: 'P', color: 'var(--avatar-2)' }, x: 1160, y: 320,
      inputs: [
        { name: 'ranked_vars', type: 'string' },
        { name: 'cnv_bed', type: 'string' },
        { name: 'sv_vcf', type: 'string' },
        { name: 'burden_q', type: 'float' },
        { name: 'exomiser_scores', type: 'string' }
      ],
      outputs: [{ name: 'interpretation_pack', type: 'string' }] },
    { id: 'md-pharmcat', type: 'Model', label: 'PharmCAT PGx', color: 'var(--dot-green)', user: { letter: 'K', color: 'var(--avatar-4)' }, x: 1420, y: 520,
      inputs: [{ name: 'pass_vcf', type: 'string' }],
      outputs: [{ name: 'pgx_alleles', type: 'string' }] },
    { id: 'md-report', type: 'Model', label: 'Clinical report (PDF + FHIR)', color: 'var(--dot-red)', user: { letter: 'P', color: 'var(--avatar-2)' }, x: 1680, y: 640,
      inputs: [
        { name: 'interpretation_pack', type: 'string' },
        { name: 'pgx_alleles', type: 'string' },
        { name: 'clinvar_tsv', type: 'string' }
      ],
      outputs: [{ name: 'report_uri', type: 'string' }] },
    { id: 'md-audit', type: 'Model', label: 'Signed audit + provenance', color: 'var(--dot-green)', user: { letter: 'B', color: '#0f172a' }, x: 1680, y: 860,
      inputs: [{ name: 'report_uri', type: 'string' }],
      outputs: [] }
  ],
  connections: [
    { from: ['ng-demux', 'out', 'fastq_r1'], to: ['ng-trim', 'in', 'fastq_r1'] },
    { from: ['ng-demux', 'out', 'fastq_r2'], to: ['ng-trim', 'in', 'fastq_r2'] },
    { from: ['ng-trim', 'out', 'clean_r1'], to: ['ng-bwa', 'in', 'clean_r1'] },
    { from: ['ng-trim', 'out', 'clean_r2'], to: ['ng-bwa', 'in', 'clean_r2'] },
    { from: ['ng-bwa', 'out', 'aligned_bam'], to: ['ng-dedup', 'in', 'aligned_bam'] },
    { from: ['ng-dedup', 'out', 'analysis_bam'], to: ['gt-hc', 'in', 'analysis_bam'] },
    { from: ['gt-hc', 'out', 'sample_gvcf'], to: ['gt-gdb', 'in', 'sample_gvcf'] },
    { from: ['gt-gdb', 'out', 'cohort_db'], to: ['gt-gt', 'in', 'cohort_db'] },
    { from: ['gt-gt', 'out', 'joint_vcf'], to: ['vcf-gate', 'in', 'joint_vcf'] },
    { from: ['vcf-gate', 'out', 'pass_vcf'], to: ['an-vep', 'in', 'pass_vcf'] },
    { from: ['an-vep', 'out', 'vep_vcf'], to: ['an-clin', 'in', 'vep_vcf'] },
    { from: ['an-clin', 'out', 'clin_vcf'], to: ['an-acmg', 'in', 'clin_vcf'] },
    { from: ['an-acmg', 'out', 'classified'], to: ['md-prioritize', 'in', 'classified'] },
    { from: ['ds-hpo', 'out', 'hpo_json'], to: ['md-prioritize', 'in', 'hpo_json'] },
    { from: ['ds-trios', 'out', 'pedigree'], to: ['md-prioritize', 'in', 'pedigree'] },
    { from: ['ds-gnomad', 'out', 'af_table'], to: ['md-prioritize', 'in', 'af_table'] },
    { from: ['ds-cohort', 'out', 'cohort_yaml'], to: ['md-prioritize', 'in', 'cohort_yaml'] },
    { from: ['ds-gnomad', 'out', 'af_table'], to: ['md-burden', 'in', 'af_table'] },
    { from: ['vcf-gate', 'out', 'pass_vcf'], to: ['md-exomiser', 'in', 'pass_vcf'] },
    { from: ['ds-hpo', 'out', 'hpo_json'], to: ['md-exomiser', 'in', 'hpo_json'] },
    { from: ['md-exomiser', 'out', 'exomiser_scores'], to: ['md-fusion', 'in', 'exomiser_scores'] },
    { from: ['vcf-gate', 'out', 'pass_vcf'], to: ['md-burden', 'in', 'pass_vcf'] },
    { from: ['ng-dedup', 'out', 'analysis_bam'], to: ['md-cnv', 'in', 'analysis_bam'] },
    { from: ['ng-dedup', 'out', 'analysis_bam'], to: ['md-sv', 'in', 'analysis_bam'] },
    { from: ['md-prioritize', 'out', 'ranked_vars'], to: ['md-fusion', 'in', 'ranked_vars'] },
    { from: ['md-cnv', 'out', 'cnv_bed'], to: ['md-fusion', 'in', 'cnv_bed'] },
    { from: ['md-sv', 'out', 'sv_vcf'], to: ['md-fusion', 'in', 'sv_vcf'] },
    { from: ['md-burden', 'out', 'burden_q'], to: ['md-fusion', 'in', 'burden_q'] },
    { from: ['vcf-gate', 'out', 'pass_vcf'], to: ['md-pharmcat', 'in', 'pass_vcf'] },
    { from: ['md-fusion', 'out', 'interpretation_pack'], to: ['md-report', 'in', 'interpretation_pack'] },
    { from: ['md-pharmcat', 'out', 'pgx_alleles'], to: ['md-report', 'in', 'pgx_alleles'] },
    { from: ['ds-clinvar', 'out', 'clinvar_tsv'], to: ['md-report', 'in', 'clinvar_tsv'] },
    { from: ['md-report', 'out', 'report_uri'], to: ['md-audit', 'in', 'report_uri'] }
  ],
  subgraphs: [
    {
      id: 'sg_seq',
      name: 'Sequencing & GRCh38',
      collapsed: true,
      nodeIds: ['ng-demux', 'ng-trim', 'ng-bwa', 'ng-dedup'],
      showInternalPins: true
    },
    {
      id: 'sg_gt',
      name: 'Joint genotyping',
      collapsed: true,
      nodeIds: ['gt-hc', 'gt-gdb', 'gt-gt'],
      showInternalPins: true
    },
    {
      id: 'sg_ann',
      name: 'Annotation & ACMG',
      collapsed: true,
      nodeIds: ['an-vep', 'an-clin', 'an-acmg'],
      showInternalPins: true
    }
  ]
};
